"use client";
import { useRouter, useSearchParams } from "next/navigation";
import { useState, useEffect, useRef } from "react";
import Image from "next/image";
import Select from "react-select";
import DashboardHeader from "@/components/common/DashboardHeader";
import MobileMenu from "@/components/common/mobile-menu";
import DboardMobileNavigation from "@/components/property/dashboard/DboardMobileNavigation";
import Footer from "@/components/property/dashboard/Footer";
import SidebarDashboard from "@/components/property/dashboard/SidebarDashboard";
import {
  createPropertymanagement,
  getPropertymanagementById,
  updatePropertymanagement,
} from "@/api/propertymanagement";


const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:5000";

const resolvePropertymanagementImageUrl = (value) => {
  if (!value) return "";
  if (value.startsWith("http")) return value;
  return `${API_BASE_URL}${value}`;
};

const AddPropertymanagement = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get("edit");
  const isEditMode = !!editId;

  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(isEditMode);
  const [showSelect, setShowSelect] = useState(false);
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);

  const statusOptions = [
    { value: "active", label: "Active" },
    { value: "inactive", label: "Inactive" },
  ];

  const [formData, setFormData] = useState({
    name: "",
    slug: "",
    email: "",
    phoneNumber: "",
    description: "",
    shortDescription: "",
    metaTitle: "",
    metaDescription: "",
    status: "active",
    imageUrl: "",
    featuredImageUrl: "",
  });
  const [selectedImageFile, setSelectedImageFile] = useState(null);
  const [imagePreviewUrl, setImagePreviewUrl] = useState("");
  const previewObjectUrlRef = useRef(null);

  const [selectedFeaturedImageFile, setSelectedFeaturedImageFile] = useState(null);
  const [featuredImagePreviewUrl, setFeaturedImagePreviewUrl] = useState("");
  const featuredPreviewObjectUrlRef = useRef(null);

  const generateSlug = (name) => {
    if (!name) return "";
    return name
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)+/g, "");
  };

  useEffect(() => {
    setShowSelect(true);
  }, []);

  useEffect(() => {
    const fetchPropertymanagement = async () => {
      if (!isEditMode) {
        setFormData({
          name: "",
          slug: "",
          email: "",
          phoneNumber: "",
          description: "",
          shortDescription: "",
          metaTitle: "",
          metaDescription: "",
          status: "active",
          imageUrl: "",
          featuredImageUrl: "",
        });
        setSlugManuallyEdited(false);
      setSelectedImageFile(null);
      setImagePreviewUrl("");
      setSelectedFeaturedImageFile(null);
      setFeaturedImagePreviewUrl("");
        setFetching(false);
        return;
      }

      if (!editId) {
        setFormData({
          name: "",
          slug: "",
          email: "",
          phoneNumber: "",
          description: "",
          shortDescription: "",
          metaTitle: "",
          metaDescription: "",
          status: "active",
          imageUrl: "",
          featuredImageUrl: "",
        });
        setSlugManuallyEdited(false);
        setFetching(false);
        return;
      }

      try {
        setFetching(true);
        const token = localStorage.getItem("adminToken");
        if (!token) {
          alert("Authentication required. Please login again.");
          router.push("/cmsadminlogin");
          return;
        }

        const response = await getPropertymanagementById(editId, token);
        if (response.status === "success" && response.data) {
          const propertymanagement = response.data;
          const propertymanagementName = propertymanagement.name || "";
          const propertymanagementSlug = propertymanagement.slug || "";
          const autoGeneratedSlug = generateSlug(propertymanagementName);

          setFormData({
            name: propertymanagementName,
            slug: propertymanagementSlug,
            email: propertymanagement.email || "",
            phoneNumber: propertymanagement.phoneNumber || "",
            description: propertymanagement.description || "",
            shortDescription: propertymanagement.shortDescription || "",
            metaTitle: propertymanagement.metaTitle || "",
            metaDescription: propertymanagement.metaDescription || "",
            status: propertymanagement.status || "active",
            imageUrl: propertymanagement.image || "",
            featuredImageUrl: propertymanagement.featuredImage || "",
          });

          setSlugManuallyEdited(
            propertymanagementSlug !== autoGeneratedSlug && propertymanagementSlug !== ""
          );
          setSelectedImageFile(null);
          setImagePreviewUrl(resolvePropertymanagementImageUrl(propertymanagement.image));
          setSelectedFeaturedImageFile(null);
          setFeaturedImagePreviewUrl(resolvePropertymanagementImageUrl(propertymanagement.featuredImage));
        } else {
          alert("Failed to load propertymanagement data");
          router.push("/cmsadminlogin/propertymanagement-list");
        }
      } catch (error) {
        console.error("Error fetching propertymanagement:", error);
        alert(error.response?.data?.message || "Failed to load propertymanagement data");
        router.push("/cmsadminlogin/propertymanagement-list");
      } finally {
        setFetching(false);
      }
    };

    fetchPropertymanagement();
  }, [editId, isEditMode, router]);

  useEffect(() => {
    if (!selectedImageFile) {
      setImagePreviewUrl(resolvePropertymanagementImageUrl(formData.imageUrl));
    }
  }, [formData.imageUrl, selectedImageFile]);

  useEffect(() => {
    if (!selectedFeaturedImageFile) {
      setFeaturedImagePreviewUrl(resolvePropertymanagementImageUrl(formData.featuredImageUrl));
    }
  }, [formData.featuredImageUrl, selectedFeaturedImageFile]);

  useEffect(() => {
    return () => {
      if (previewObjectUrlRef.current) {
        URL.revokeObjectURL(previewObjectUrlRef.current);
        previewObjectUrlRef.current = null;
      }
      if (featuredPreviewObjectUrlRef.current) {
        URL.revokeObjectURL(featuredPreviewObjectUrlRef.current);
        featuredPreviewObjectUrlRef.current = null;
      }
    };
  }, []);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => {
      if (name === "name") {
        return {
          ...prev,
          name: value,
          slug: slugManuallyEdited ? prev.slug : generateSlug(value),
        };
      }
      if (name === "slug") {
        setSlugManuallyEdited(true);
      }
      return {
        ...prev,
        [name]: value,
      };
    });
  };

  const handleImageChange = (e) => {
    const file = e.target.files ? e.target.files[0] : null;
    setSelectedImageFile(file);

    if (previewObjectUrlRef.current) {
      URL.revokeObjectURL(previewObjectUrlRef.current);
      previewObjectUrlRef.current = null;
    }

    if (file) {
      const previewUrl = URL.createObjectURL(file);
      previewObjectUrlRef.current = previewUrl;
      setImagePreviewUrl(previewUrl);
    } else {
      setImagePreviewUrl(formData.imageUrl);
    }
  };

  const handleFeaturedImageChange = (e) => {
    const file = e.target.files ? e.target.files[0] : null;
    setSelectedFeaturedImageFile(file);

    if (featuredPreviewObjectUrlRef.current) {
      URL.revokeObjectURL(featuredPreviewObjectUrlRef.current);
      featuredPreviewObjectUrlRef.current = null;
    }

    if (file) {
      const previewUrl = URL.createObjectURL(file);
      featuredPreviewObjectUrlRef.current = previewUrl;
      setFeaturedImagePreviewUrl(previewUrl);
    } else {
      setFeaturedImagePreviewUrl(formData.featuredImageUrl);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setLoading(true);
      const nameValue = formData.name.trim();
      const slugValue = formData.slug.trim() || generateSlug(formData.name);
      const descriptionValue = formData.description.trim();
      const payload = new FormData();
      payload.append("name", nameValue);
      payload.append("slug", slugValue);
      payload.append("email", formData.email.trim().toLowerCase());
      payload.append("phoneNumber", formData.phoneNumber.trim());
      payload.append("description", descriptionValue);
      payload.append("shortDescription", (formData.shortDescription || "").trim());
      payload.append("metaTitle", (formData.metaTitle || "").trim());
      payload.append("metaDescription", (formData.metaDescription || "").trim());
      payload.append("status", formData.status || "active");
      if (selectedImageFile) {
        payload.append("image", selectedImageFile);
      }
      if (selectedFeaturedImageFile) {
        payload.append("featuredImage", selectedFeaturedImageFile);
      }

      const token = localStorage.getItem("adminToken");
      if (!token) {
        alert("Authentication required. Please login again.");
        router.push("/cmsadminlogin");
        return;
      }

      let res;
      if (isEditMode) {
        res = await updatePropertymanagement(editId, payload, token);
        if (res.status === "success") {
          alert("Propertymanagement updated successfully!");
          router.push("/cmsadminlogin/propertymanagement-list");
        } else {
          alert(res.message || "Something went wrong!");
        }
      } else {
        res = await createPropertymanagement(payload, token);
        if (res.status === "success") {
          alert("Propertymanagement created successfully!");
          router.push("/cmsadminlogin/propertymanagement-list");
        } else {
          alert(res.message || "Something went wrong!");
        }
      }
    } catch (error) {
      console.error(
        `Error ${isEditMode ? "updating" : "creating"} propertymanagement:`,
        error
      );
      const errorMessage =
        error.response?.data?.message ||
        error.message ||
        `Failed to ${
          isEditMode ? "update" : "create"
        } propertymanagement. Please try again.`;
      alert(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => router.back();

  return (
    <>
      <DashboardHeader />
      <MobileMenu />
      <div className="dashboard_content_wrapper">
        <div className="dashboard dashboard_wrapper pr30 pr0-md">
          <SidebarDashboard />

          <div className="dashboard__main pl0-md">
            <div className="dashboard__content property-page bgc-f7">
              <div className="row pb40 d-block d-lg-none">
                <div className="col-lg-12">
                  <DboardMobileNavigation />
                </div>
              </div>

              <div className="row align-items-center pb40">
                <div className="col-lg-12">
                  <div className="dashboard_title_area">
                    <h2>
                      {isEditMode ? "Edit Propertymanagement" : "Add a New Propertymanagement"}
                    </h2>
                    <p
                      className="text"
                      style={{
                        fontSize: "16px",
                        color: "#6c757d",
                        marginTop: "8px",
                      }}
                    >
                      {isEditMode
                        ? "Update propertymanagement profile information."
                        : "Create an propertymanagement profile to associate with real estate projects and listings."}
                    </p>
                  </div>
                </div>
              </div>

              <div className="row">
                <div className="col-xl-12">
                  <div className="ps-widget bgc-white bdrs12 default-box-shadow2 p30 mb30 overflow-hidden position-relative">
                    <div className="mb40">
                      <h4
                        className="title fz17 mb30"
                        style={{ fontWeight: "600", color: "#111827" }}
                      >
                        {isEditMode ? "Edit Propertymanagement" : "Create Propertymanagement"}
                      </h4>
                      {fetching ? (
                        <div className="text-center py-4">
                          <p>Loading propertymanagement data...</p>
                        </div>
                      ) : (
                        <form className="form-style1" onSubmit={handleSubmit}>
                          <div className="row">
                            <div className="col-sm-6 col-xl-12">
                              <div className="row">
                                <div className="col-sm-4">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Propertymanagement Name
                                    </label>
                                    <input
                                      type="text"
                                      name="name"
                                      className="form-control"
                                      placeholder="Enter propertymanagement name"
                                      value={formData.name}
                                      onChange={handleInputChange}
                                      required
                                    />
                                  </div>
                                </div>

                                <div className="col-sm-4">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Propertymanagement Slug (SEO URL){" "}
                                      <span
                                        style={{
                                          fontSize: "12px",
                                          color: "#6b7280",
                                          fontWeight: "normal",
                                        }}
                                      >
                                        (Auto-generated)
                                      </span>
                                    </label>
                                    <input
                                      type="text"
                                      name="slug"
                                      className="form-control"
                                      placeholder="Auto-generated from name"
                                      value={formData.slug}
                                      onChange={handleInputChange}
                                    />
                                    <p
                                      className="text mt10"
                                      style={{ fontSize: "12px", color: "#6b7280" }}
                                    >
                                      Slug is auto-generated from name. You can edit it manually if
                                      needed.
                                    </p>
                                  </div>
                                </div>

                                <div className="col-sm-4">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Email
                                    </label>
                                    <input
                                      type="email"
                                      name="email"
                                      className="form-control"
                                      placeholder="Enter email address"
                                      value={formData.email}
                                      onChange={handleInputChange}
                                      required
                                    />
                                  </div>
                                </div>

                                <div className="col-sm-4">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Phone Number
                                    </label>
                                    <input
                                      type="text"
                                      name="phoneNumber"
                                      className="form-control"
                                      placeholder="Enter phone number"
                                      value={formData.phoneNumber}
                                      onChange={handleInputChange}
                                      required
                                    />
                                  </div>
                                </div>

                                <div className="col-sm-4">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Description
                                    </label>
                                    <textarea
                                      name="description"
                                      cols={30}
                                      rows={5}
                                      className="form-control"
                                      placeholder="Enter propertymanagement description"
                                      value={formData.description}
                                      onChange={handleInputChange}
                                    />
                                  </div>
                                </div>

                                <div className="col-sm-4">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Short Description
                                    </label>
                                    <textarea
                                      name="shortDescription"
                                      cols={30}
                                      rows={3}
                                      className="form-control"
                                      placeholder="Enter short description"
                                      value={formData.shortDescription}
                                      onChange={handleInputChange}
                                    />
                                  </div>
                                </div>

                                <div className="col-sm-12">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Profile Image
                                    </label>
                                    <input
                                      type="file"
                                      accept="image/*"
                                      className="form-control"
                                      onChange={handleImageChange}
                                    />
                                    <small
                                      className="text-muted d-block mt10"
                                      style={{ fontSize: "12px" }}
                                    >
                                      Upload a square image for the propertymanagement profile.
                                      Supported formats: JPG, PNG, or WebP.
                                    </small>
                                    {imagePreviewUrl && (
                                      <div
                                        className="mt15"
                                        style={{
                                          maxWidth: "160px",
                                          maxHeight: "160px",
                                          overflow: "hidden",
                                          borderRadius: "12px",
                                          border: "1px solid #E5E7EB",
                                          position: "relative",
                                        }}
                                      >
                                        <Image
                                          src={imagePreviewUrl}
                                          alt="Propertymanagement preview"
                                          fill
                                          sizes="160px"
                                          unoptimized
                                          style={{ objectFit: "cover", display: "block" }}
                                        />
                                      </div>
                                    )}
                                  </div>
                                </div>

                                <div className="col-sm-12">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Featured Image
                                    </label>
                                    <input
                                      type="file"
                                      accept="image/*"
                                      className="form-control"
                                      onChange={handleFeaturedImageChange}
                                    />
                                    <small
                                      className="text-muted d-block mt10"
                                      style={{ fontSize: "12px" }}
                                    >
                                      Upload a featured image for the propertymanagement.
                                      Supported formats: JPG, PNG, or WebP.
                                    </small>
                                    {featuredImagePreviewUrl && (
                                      <div
                                        className="mt15"
                                        style={{
                                          maxWidth: "320px",
                                          maxHeight: "200px",
                                          overflow: "hidden",
                                          borderRadius: "12px",
                                          border: "1px solid #E5E7EB",
                                          position: "relative",
                                        }}
                                      >
                                        <Image
                                          src={featuredImagePreviewUrl}
                                          alt="Featured image preview"
                                          fill
                                          sizes="320px"
                                          unoptimized
                                          style={{ objectFit: "cover", display: "block" }}
                                        />
                                      </div>
                                    )}
                                  </div>
                                </div>

                                <div className="col-sm-12">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Meta Title (SEO)
                                    </label>
                                    <input
                                      type="text"
                                      name="metaTitle"
                                      className="form-control"
                                      placeholder="Enter meta title for SEO"
                                      value={formData.metaTitle}
                                      onChange={handleInputChange}
                                    />
                                    <p
                                      className="text mt10"
                                      style={{ fontSize: "12px", color: "#6b7280" }}
                                    >
                                      If empty, the propertymanagement name will be used on the propertymanagement detail
                                      page.
                                    </p>
                                  </div>
                                </div>

                                <div className="col-sm-12">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Meta Description (SEO)
                                    </label>
                                    <textarea
                                      name="metaDescription"
                                      cols={30}
                                      rows={3}
                                      className="form-control"
                                      placeholder="Enter meta description for SEO"
                                      value={formData.metaDescription}
                                      onChange={handleInputChange}
                                    />
                                    <p
                                      className="text mt10"
                                      style={{ fontSize: "12px", color: "#6b7280" }}
                                    >
                                      If empty, the propertymanagement description will be used on the propertymanagement
                                      detail page.
                                    </p>
                                  </div>
                                </div>

                                

                                <div className="col-sm-6 col-xl-3">
                                  <div className="mb30">
                                    <label className="heading-color ff-heading fw600 mb10">
                                      Status
                                    </label>
                                    <div className="location-area">
                                      {showSelect && (
                                        <Select
                                          key={formData.status}
                                          options={statusOptions}
                                          value={statusOptions.find(
                                            (opt) =>
                                              opt.value === formData.status
                                          ) || statusOptions[0]}
                                          onChange={(selected) => {
                                            if (selected) {
                                              setFormData((prev) => ({
                                                ...prev,
                                                status: selected.value,
                                              }));
                                            }
                                          }}
                                          styles={{
                                            control: (styles) => ({
                                              ...styles,
                                              backgroundColor: "#fff",
                                              border: "1px solid #E5E7EB",
                                              borderRadius: "6px",
                                              fontSize: "16px",
                                              color: "#111827",
                                              minHeight: "auto",
                                              height: "auto",
                                              padding: "6px 12px",
                                              width: "auto",
                                              minWidth: "120px",
                                              "&:hover": {
                                                borderColor: "#FC9401",
                                                cursor: "pointer",
                                              },
                                              "&:focus-within": {
                                                borderColor: "#FC9401",
                                                boxShadow: "0 0 0 1px #FC9401",
                                              },
                                            }),
                                            option: (
                                              styles,
                                              { isFocused, isSelected }
                                            ) => ({
                                              ...styles,
                                              backgroundColor: isSelected
                                                ? "#FC9401"
                                                : isFocused
                                                ? "#F9FAFB"
                                                : "#fff",
                                              color: isSelected
                                                ? "#fff"
                                                : "#111827",
                                              cursor: "pointer",
                                              fontSize: "16px",
                                              padding: "12px 16px",
                                              minHeight: "48px",
                                            }),
                                            menu: (styles) => ({
                                              ...styles,
                                              backgroundColor: "#fff",
                                              border: "1px solid #E5E7EB",
                                              borderRadius: "6px",
                                              boxShadow:
                                                "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
                                              zIndex: 9999,
                                              padding: "8px 0",
                                              marginTop: "4px",
                                            }),
                                            placeholder: (styles) => ({
                                              ...styles,
                                              color: "#9CA3AF",
                                              fontSize: "16px",
                                            }),
                                            singleValue: (styles) => ({
                                              ...styles,
                                              color: "#111827",
                                              fontSize: "16px",
                                            }),
                                            dropdownIndicator: (styles) => ({
                                              ...styles,
                                              color: "#6B7280",
                                              "&:hover": {
                                                color: "#FC9401",
                                              },
                                            }),
                                            indicatorSeparator: (styles) => ({
                                              ...styles,
                                              backgroundColor: "#E5E7EB",
                                            }),
                                          }}
                                          className="select-custom pl-0"
                                          classNamePrefix="select"
                                          isSearchable={false}
                                          required
                                        />
                                      )}
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>

                          <div className="row mt30">
                            <div className="col-12">
                              <div className="d-flex gap-3">
                                <button
                                  type="button"
                                  className="ud-btn btn-white"
                                  onClick={handleBack}
                                  style={{ minWidth: "120px" }}
                                >
                                  Back
                                </button>
                                <button
                                  type="submit"
                                  className="ud-btn btn-thm"
                                  style={{ minWidth: "120px" }}
                                  disabled={loading}
                                >
                                  {loading
                                    ? "Processing..."
                                    : isEditMode
                                    ? "Update"
                                    : "Submit"}
                                </button>
                              </div>
                            </div>
                          </div>
                        </form>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <Footer />
          </div>
        </div>
      </div>
    </>
  );
};

export default AddPropertymanagement;
