"use client";
import React, { useState, useEffect, useRef } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Select from "react-select";
import Image from "next/image";
import { createBlog, getBlogById, updateBlog } from "@/api/blog";
import { getAllBlogCategories } from "@/api/blogCategory";

const customStyles = {
  option: (styles, { isFocused, isSelected, isHovered }) => {
    return {
      ...styles,
      backgroundColor: isSelected
        ? "#FC9401"
        : isHovered
        ? "#eb675312"
        : isFocused
        ? "#eb675312"
        : undefined,
    };
  },
};

const AddBlogForm = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const editId = searchParams.get("editId");
  const isEditMode = !!editId;

  const [showSelect, setShowSelect] = useState(false);
  const [loading, setLoading] = useState(false);
  const [fetchingBlog, setFetchingBlog] = useState(isEditMode);
  const [fetchingCategories, setFetchingCategories] = useState(true);
  const [uploadedImage, setUploadedImage] = useState(null);
  const [imageFile, setImageFile] = useState(null);
  const [blogCategories, setBlogCategories] = useState([]);
  const [blogCategoryOptions, setBlogCategoryOptions] = useState([]);
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false);
  const fileInputRef = useRef(null);

  const [formData, setFormData] = useState({
    blogCategory: "",
    blogTitle: "",
    blogSlug: "",
    blogSource: "",
    blogDate: "",
    description: "",
    tags: "",
    metaTitle: "",
    metaDescription: "",
    status: "active",
  });

  const statusOptions = [
    { value: "active", label: "Active" },
    { value: "inactive", label: "Inactive" },
  ];

  useEffect(() => {
    setShowSelect(true);
    fetchBlogCategories();
  }, []);

  useEffect(() => {
    if (!isEditMode && !editId) {
      setFormData({
        blogCategory: "",
        blogTitle: "",
        blogSlug: "",
        blogSource: "",
        blogDate: "",
        description: "",
        tags: "",
        metaTitle: "",
        metaDescription: "",
        status: "active",
      });
      setUploadedImage(null);
      setImageFile(null);
      setSlugManuallyEdited(false);
      setFetchingBlog(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = "";
      }
    }
  }, [isEditMode, editId]);

  useEffect(() => {
    const fetchBlogData = async () => {
      if (!isEditMode || !editId) {
        setFetchingBlog(false);
        return;
      }

      try {
        setFetchingBlog(true);
        const token = localStorage.getItem("adminToken");
        if (!token) {
          alert("Authentication required. Please login again.");
          router.push("/cmsadminlogin");
          return;
        }

        const response = await getBlogById(editId, token);
        if (response.status === "success" && response.data) {
          const blog = response.data;
          const blogTitle = blog.title || "";
          const blogSlug = blog.slug || "";
          const autoGeneratedSlug = generateSlug(blogTitle);

          setFormData({
            blogCategory: blog.blogCategory?._id || blog.blogCategory || "",
            blogTitle: blogTitle,
            blogSlug: blogSlug,
            blogSource: blog.source || "",
            blogDate: blog.date
              ? new Date(blog.date).toISOString().split("T")[0]
              : "",
            description: blog.description || "",
            tags: blog.tags && Array.isArray(blog.tags) ? blog.tags.join(", ") : "",
            metaTitle: blog.metaTitle || "",
            metaDescription: blog.metaDescription || "",
            status: blog.status || "active",
          });

          setSlugManuallyEdited(
            blogSlug !== autoGeneratedSlug && blogSlug !== ""
          );

          if (blog.image) {
            const imageUrl = blog.image.startsWith("http")
              ? blog.image
              : `${
                  process.env.NEXT_PUBLIC_API_BASE_URL ||
                  "http://localhost:5000"
                }${blog.image}`;
            setUploadedImage(imageUrl);
          }
        } else {
          alert("Failed to load blog data");
          router.push("/cmsadminlogin/blog-list");
        }
      } catch (error) {
        console.error("Error fetching blog:", error);
        alert(error.response?.data?.message || "Failed to load blog data");
        router.push("/cmsadminlogin/blog-list");
      } finally {
        setFetchingBlog(false);
      }
    };

    fetchBlogData();
  }, [isEditMode, editId, router]);

  const fetchBlogCategories = async () => {
    try {
      setFetchingCategories(true);
      const token = localStorage.getItem("adminToken");
      if (!token) {
        setFetchingCategories(false);
        console.error("No authentication token found");
        return;
      }

      const response = await getAllBlogCategories(token);

      if (response.status === "success" && response.data) {
        setBlogCategories(response.data);
        const options = response.data.map((cat) => ({
          value: cat._id,
          label: cat.title,
        }));
        setBlogCategoryOptions(options);
      } else {
        console.error("Unexpected response format:", response);
        setBlogCategoryOptions([]);
      }
    } catch (error) {
      console.error("Error fetching blog categories:", error);
      console.error("Error details:", error.response?.data || error.message);
      alert("Failed to load blog categories. Please refresh the page.");
      setBlogCategoryOptions([]);
    } finally {
      setFetchingCategories(false);
    }
  };

  const generateSlug = (title) => {
    if (!title) return "";
    return title
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)+/g, "");
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => {
      if (name === "blogTitle") {
        return {
          ...prev,
          blogTitle: value,
          blogSlug: slugManuallyEdited ? prev.blogSlug : generateSlug(value),
        };
      }
      if (name === "blogSlug") {
        setSlugManuallyEdited(true);
      }
      return {
        ...prev,
        [name]: value,
      };
    });
  };

  const handleImageUpload = (files) => {
    if (files && files[0]) {
      const file = files[0];
      setImageFile(file);
      const reader = new FileReader();
      reader.onload = (e) => {
        setUploadedImage(e.target.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleImageDelete = () => {
    setUploadedImage(null);
    setImageFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!formData.blogTitle.trim()) {
      alert("Please fill in the blog title");
      return;
    }

    if (!formData.blogCategory) {
      alert("Please select a blog category");
      return;
    }

    if (!formData.description.trim()) {
      alert("Please fill in the blog description");
      return;
    }

    try {
      setLoading(true);
      const token = localStorage.getItem("adminToken");

      if (!token) {
        alert("Authentication required. Please login again.");
        router.push("/cmsadminlogin");
        return;
      }

      // Prepare blog data
      const tagsArray = formData.tags
        ? formData.tags
            .split(",")
            .map((tag) => tag.trim())
            .filter((tag) => tag.length > 0)
        : [];

      const blogData = {
        title: formData.blogTitle.trim(),
        blogCategory: formData.blogCategory,
        slug: formData.blogSlug.trim() || generateSlug(formData.blogTitle),
        source: formData.blogSource.trim() || "",
        date: formData.blogDate || new Date().toISOString(),
        description: formData.description.trim(),
        tags: tagsArray,
        metaTitle: formData.metaTitle.trim() || "",
        metaDescription: formData.metaDescription.trim() || "",
        status: formData.status || "active",
      };

      if (imageFile) {
        blogData.image = imageFile;
      }

      let response;
      if (isEditMode && editId) {
        response = await updateBlog(editId, blogData, token);
        if (response.status === "success") {
          alert("Blog updated successfully!");
          router.push("/cmsadminlogin/blog-list");
        } else {
          alert(response.message || "Failed to update blog");
        }
      } else {
        response = await createBlog(blogData, token);
        if (response.status === "success") {
          alert("Blog created successfully!");

          setFormData({
            blogCategory: "",
            blogTitle: "",
            blogSlug: "",
            blogSource: "",
            blogDate: "",
            description: "",
            tags: "",
            metaTitle: "",
            metaDescription: "",
            status: "active",
          });
          setUploadedImage(null);
          setImageFile(null);
          if (fileInputRef.current) {
            fileInputRef.current.value = "";
          }
          router.push("/cmsadminlogin/blog-list");
        } else {
          alert(response.message || "Failed to create blog");
        }
      }
    } catch (error) {
      console.error(
        `Error ${isEditMode ? "updating" : "creating"} blog:`,
        error
      );
      console.error("Error details:", error);

      let errorMessage = `Failed to ${isEditMode ? "update" : "create"} blog`;

      if (error?.message) {
        errorMessage = error.message;
      } else if (error?.response?.data?.message) {
        errorMessage = error.response.data.message;
      } else if (typeof error === "string") {
        errorMessage = error;
      }

      alert(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleBack = () => {
    router.back();
  };

  if (fetchingBlog) {
    return (
      <div className="text-center py-4">
        <p>Loading blog data...</p>
      </div>
    );
  }

  return (
    <form className="form-style1" onSubmit={handleSubmit}>
      {/* Create Listing Section */}
      <div className="mb40">
        <h4
          className="title fz17 mb30"
          style={{ fontWeight: "600", color: "#111827" }}
        >
          {isEditMode ? "Edit Listing" : "Create Listing"}
        </h4>
        <div className="row">
          {/* Image Upload */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Upload Photo
              </label>
              <div
                className="upload-img position-relative overflow-hidden bdrs12 text-center mb20"
                style={{
                  minHeight: "260px",
                  border: "1px solid #e5e7eb",
                  backgroundColor: "#f9fafb",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  justifyContent: "center",
                  padding: "20px",
                }}
              >
                {uploadedImage ? (
                  <>
                    <div
                      className="position-relative mb20"
                      style={{ width: "260px", height: "260px" }}
                    >
                      <Image
                        src={uploadedImage}
                        alt="Blog image"
                        fill
                        style={{ objectFit: "cover", borderRadius: "8px" }}
                      />
                      <button
                        type="button"
                        className="tag-del"
                        onClick={handleImageDelete}
                        style={{
                          position: "absolute",
                          top: "5px",
                          right: "5px",
                          border: "none",
                          background: "rgba(0,0,0,0.5)",
                          borderRadius: "50%",
                          width: "30px",
                          height: "30px",
                          color: "white",
                          cursor: "pointer",
                        }}
                      >
                        <span className="fas fa-times" />
                      </button>
                    </div>
                    <label
                      className="ud-btn btn-white"
                      style={{ cursor: "pointer" }}
                    >
                      Change Photo
                      <input
                        ref={fileInputRef}
                        type="file"
                        accept="image/*"
                        style={{ display: "none" }}
                        onChange={(e) => handleImageUpload(e.target.files)}
                      />
                    </label>
                  </>
                ) : (
                  <>
                    <div
                      className="mb20"
                      style={{ fontSize: "48px", color: "#9ca3af" }}
                    >
                      260X260
                    </div>
                    <label
                      className="ud-btn btn-white"
                      style={{ cursor: "pointer" }}
                    >
                      <span className="flaticon-upload me-2" />
                      Upload Photo
                      <input
                        ref={fileInputRef}
                        type="file"
                        accept="image/*"
                        style={{ display: "none" }}
                        onChange={(e) => handleImageUpload(e.target.files)}
                      />
                    </label>
                    <p
                      className="text mt10"
                      style={{ fontSize: "12px", color: "#6b7280" }}
                    >
                      minimum 260px x 260px
                    </p>
                  </>
                )}
              </div>
            </div>
          </div>
          {/* End Image Upload */}

          {/* Blog Category */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Select Blog category
              </label>
              <div className="location-area">
                {showSelect && !fetchingCategories && (
                  <Select
                    styles={customStyles}
                    className="select-custom pl-0"
                    classNamePrefix="select"
                    required
                    options={blogCategoryOptions}
                    value={
                      formData.blogCategory
                        ? blogCategoryOptions.find(
                            (opt) => opt.value === formData.blogCategory
                          )
                        : null
                    }
                    onChange={(selected) =>
                      setFormData((prev) => ({
                        ...prev,
                        blogCategory: selected?.value || "",
                      }))
                    }
                    placeholder={
                      blogCategoryOptions.length > 0
                        ? "-- Select Blog category --"
                        : "No categories available"
                    }
                    isDisabled={blogCategoryOptions.length === 0}
                  />
                )}
                {fetchingCategories && (
                  <div className="text-muted" style={{ padding: "8px 0" }}>
                    Loading categories...
                  </div>
                )}
              </div>
            </div>
          </div>
          {/* End Blog Category */}

          {/* Blog Title */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Blog Title
              </label>
              <input
                type="text"
                name="blogTitle"
                className="form-control"
                placeholder="Enter blog title"
                value={formData.blogTitle}
                onChange={handleInputChange}
                required
              />
            </div>
          </div>
          {/* End Blog Title */}

          {/* Blog Slug */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Blog Slug (SEO URL){" "}
                <span
                  style={{
                    fontSize: "12px",
                    color: "#6b7280",
                    fontWeight: "normal",
                  }}
                >
                  (Auto-generated)
                </span>
              </label>
              <input
                type="text"
                name="blogSlug"
                className="form-control"
                placeholder="Auto-generated from title"
                value={formData.blogSlug}
                onChange={handleInputChange}
              />
              <p
                className="text mt10"
                style={{ fontSize: "12px", color: "#6b7280" }}
              >
                Slug is auto-generated from title. You can edit it manually if
                needed.
              </p>
            </div>
          </div>
          {/* End Blog Slug */}

          {/* Blog Source */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Blog Source
              </label>
              <input
                type="text"
                name="blogSource"
                className="form-control"
                placeholder="Enter blog source"
                value={formData.blogSource}
                onChange={handleInputChange}
              />
            </div>
          </div>
          {/* End Blog Source */}

          {/* Blog Date */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Blog Date
              </label>
              <input
                type="date"
                name="blogDate"
                className="form-control"
                value={formData.blogDate}
                onChange={handleInputChange}
              />
            </div>
          </div>
          {/* End Blog Date */}

          {/* Tags */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Tags
              </label>
              <input
                type="text"
                name="tags"
                className="form-control"
                placeholder="Enter tags (comma-separated)"
                value={formData.tags}
                onChange={handleInputChange}
              />
              <p
                className="text mt10"
                style={{ fontSize: "12px", color: "#6b7280" }}
              >
                Separate multiple tags with commas
              </p>
            </div>
          </div>
          {/* End Tags */}

          {/* Status */}
          <div className="col-sm-6 col-xl-4">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Status
              </label>
              <div className="location-area">
                {showSelect && (
                  <Select
                    options={statusOptions}
                    value={statusOptions.find(
                      (opt) => opt.value === formData.status
                    )}
                    onChange={(selected) =>
                      setFormData((prev) => ({
                        ...prev,
                        status: selected?.value || "active",
                      }))
                    }
                    styles={{
                      control: (styles) => ({
                        ...styles,
                        backgroundColor: "#fff",
                        border: "1px solid #E5E7EB",
                        borderRadius: "6px",
                        fontSize: "16px",
                        color: "#111827",
                        minHeight: "auto",
                        height: "auto",
                        padding: "6px 12px",
                        width: "auto",
                        minWidth: "120px",
                        "&:hover": {
                          borderColor: "#FC9401",
                          cursor: "pointer",
                        },
                        "&:focus-within": {
                          borderColor: "#FC9401",
                          boxShadow: "0 0 0 1px #FC9401",
                        },
                      }),
                      option: (styles, { isFocused, isSelected }) => ({
                        ...styles,
                        backgroundColor: isSelected
                          ? "#FC9401"
                          : isFocused
                          ? "#F9FAFB"
                          : "#fff",
                        color: isSelected ? "#fff" : "#111827",
                        cursor: "pointer",
                        fontSize: "16px",
                        padding: "12px 16px",
                        minHeight: "48px",
                      }),
                      menu: (styles) => ({
                        ...styles,
                        backgroundColor: "#fff",
                        border: "1px solid #E5E7EB",
                        borderRadius: "6px",
                        boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
                        zIndex: 9999,
                        padding: "8px 0",
                        marginTop: "4px",
                      }),
                      placeholder: (styles) => ({
                        ...styles,
                        color: "#9CA3AF",
                        fontSize: "16px",
                      }),
                      singleValue: (styles) => ({
                        ...styles,
                        color: "#111827",
                        fontSize: "16px",
                      }),
                      dropdownIndicator: (styles) => ({
                        ...styles,
                        color: "#6B7280",
                        "&:hover": {
                          color: "#FC9401",
                        },
                      }),
                      indicatorSeparator: (styles) => ({
                        ...styles,
                        backgroundColor: "#E5E7EB",
                      }),
                    }}
                    className="select-custom pl-0"
                    classNamePrefix="select"
                    isSearchable={false}
                    required
                  />
                )}
              </div>
            </div>
          </div>
          {/* End Status */}
        </div>
        {/* End .row */}

        {/* Description */}
        <div className="row">
          <div className="col-sm-12">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Description
              </label>
              <textarea
                name="description"
                cols={30}
                rows={5}
                className="form-control"
                placeholder="Enter blog description"
                value={formData.description}
                onChange={handleInputChange}
                required
              />
            </div>
          </div>
        </div>
        {/* End .row */}
      </div>
      {/* End Create Listing Section */}

      {/* Meta Information Section */}
      <div className="mb40">
        <h4
          className="title fz17 mb30"
          style={{ fontWeight: "600", color: "#111827" }}
        >
          Meta Information
        </h4>
        <div className="row">
          <div className="col-sm-12">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Meta Title
              </label>
              <input
                type="text"
                name="metaTitle"
                className="form-control"
                placeholder="Enter meta title for SEO"
                value={formData.metaTitle}
                onChange={handleInputChange}
              />
            </div>
          </div>
          {/* End .col-12 */}

          <div className="col-sm-12">
            <div className="mb30">
              <label className="heading-color ff-heading fw600 mb10">
                Meta Description
              </label>
              <textarea
                name="metaDescription"
                cols={30}
                rows={4}
                className="form-control"
                placeholder="Enter meta description for SEO"
                value={formData.metaDescription}
                onChange={handleInputChange}
              />
            </div>
          </div>
          {/* End .col-12 */}
        </div>
        {/* End .row */}
      </div>
      {/* End Meta Information Section */}

      {/* Action Buttons */}
      <div className="row mt30">
        <div className="col-12">
          <div className="d-flex gap-3">
            <button
              type="button"
              className="ud-btn btn-white"
              onClick={handleBack}
              style={{ minWidth: "120px" }}
            >
              Back
            </button>
            <button
              type="submit"
              className="ud-btn btn-thm"
              style={{ minWidth: "120px" }}
              disabled={loading}
            >
              {loading
                ? isEditMode
                  ? "Updating..."
                  : "Submitting..."
                : isEditMode
                ? "Update"
                : "Submit"}
            </button>
          </div>
        </div>
      </div>
      {/* End .row */}
    </form>
  );
};

export default AddBlogForm;
